package br.com.si.CrudApp.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.hateoas.RepresentationModel;

import javax.persistence.*;
import java.util.Date;

@Entity
@Table(name = "employer")
@AllArgsConstructor
@NoArgsConstructor
@ApiModel(value = "Employer Model V2")
public class EmployerModelV2 extends RepresentationModel {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Setter @Getter
    @ApiModelProperty(notes = "The ID, auto generated by database", required = true)
    private long id;

    @Column(name = "name", nullable = false, length = 50)
    @Setter @Getter
    @ApiModelProperty(notes = "The event name", required = true)
    private String name;

    @Column(name = "age", nullable = true)
    @Getter @Setter
    @ApiModelProperty(notes = "The event date", required = true)
    private  Date age;

    @Column(name = "cargo", nullable = true)
    @Getter @Setter
    @ApiModelProperty(notes = "The event date", required = true)
    private String cargo;

@ManyToOne
    @JoinColumn(name = "movel_id")
    @Getter @Setter
    private MovelModel model;

}
